### ISSUE TITLE
Please update this to support newer versions of kubernetes

### ISSUE THREAD

**Issue by TazTheManiac** [luisico/cert-manager-webhook-infoblox-wapi#10]
The v1beta1.PriorityLevelConfiguration, and v1beta1.FlowSchema are deprecated, please update to use the v1 versions of both as mentioned in the deprecation notice https://kubernetes.io/docs/reference/using-api/deprecation-guide/.

**Comment by luisico** [comment]
Hi, I'm no longer maintaining the repo, feel free to fork. Thanks
