### ISSUE TITLE
Unable to get this to install

### ISSUE THREAD

**Issue by cccsss01** [luisico/cert-manager-webhook-infoblox-wapi#7]
helm repo add cert-manager-webhook-infoblox-wapi https://luisico.github.io/cert-manager-webhook-infoblox-wapi
helm repo update with both helm install instructions.

helm -n cert-manager install cert-manager-webhook-infoblox-wapi deploy/cert-manager-webhook-infoblox-wapi
Error: INSTALLATION FAILED: failed to download "deploy/cert-manager-webhook-infoblox-wapi"

 helm install my-cert-manager-webhook-infoblox-wapi cert-manager-webhook-infoblox-wapi/cert-manager-webhook-infoblox-wapi --version 1.5.2 -f values.yaml
Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded

**Comment by luisico** [comment]
Hi, I'm no longer maintaining the repo, feel free to fork. Thanks
